apiVersion: v1
kind: Service
metadata:
  name: restaurant-management
  labels:
    app: restaurant-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: restaurant-management