apiVersion: v1
kind: Service
metadata:
  name: delivery-management
  labels:
    app: delivery-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery-management