---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  labels:
    app: order-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
        - name: order-management
          image: username/order-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-management
  labels:
    app: delivery-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-management
  template:
    metadata:
      labels:
        app: delivery-management
    spec:
      containers:
        - name: delivery-management
          image: username/delivery-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-management
  labels:
    app: restaurant-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-management
  template:
    metadata:
      labels:
        app: restaurant-management
    spec:
      containers:
        - name: restaurant-management
          image: username/restaurant-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventcollections
  labels:
    app: eventcollections
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventcollections
  template:
    metadata:
      labels:
        app: eventcollections
    spec:
      containers:
        - name: eventcollections
          image: username/eventcollections:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: order-management
  labels:
    app: order-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: order-management


---


apiVersion: v1
kind: Service
metadata:
  name: delivery-management
  labels:
    app: delivery-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery-management


---


apiVersion: v1
kind: Service
metadata:
  name: restaurant-management
  labels:
    app: restaurant-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: restaurant-management


---


apiVersion: v1
kind: Service
metadata:
  name: eventcollections
  labels:
    app: eventcollections
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: eventcollections

